controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

app_livre_search:
  path: /search
  controller: App\Controller\LivreController::search
  methods: [GET, POST]
